spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/postmen_bridge?createDatabaseIfNotExist=true
    password: 290903
  rabbitmq:
    password: guest
    port: 5672
    host: 23.23.181.187
    addresses: 23.23.181.187
    username: guest
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8080
